#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for relative symlinks.
while [ -h "$app_path" ]; do
    ls=$(ls -ld "$app_path")
    link=$(expr "$ls" : '.*-> \(.*\)$')
    if expr "$link" : '/.*' > /dev/null; then
        app_path="$link"
    else
        app_path="$(dirname "$app_path")/$link"
    fi
done

APP_BASE_NAME=${0##*/}
APP_HOME=$(cd "$(dirname "$app_path")" && pwd -P || exit)

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$(uname)" in
  CYGWIN* ) cygwin=true ;;
  Darwin* ) darwin=true ;;
  MINGW* ) msys=true ;;
  NONSTOP* ) nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        # Try finding Java from Android Studio on Mac
        if [ -d "/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin" ]; then
            export JAVA_HOME="/Applications/Android Studio.app/Contents/jbr/Contents/Home"
            JAVACMD="$JAVA_HOME/bin/java"
        elif [ -d "$HOME/Library/Java/JavaVirtualMachines" ]; then
            JVM_DIR=$(find "$HOME/Library/Java/JavaVirtualMachines" -name "java" -type f | head -n 1)
            if [ -n "$JVM_DIR" ]; then
                JAVACMD="$JVM_DIR"
            fi
        fi
    fi
    if ! command -v "$JAVACMD" >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if [ "$cygwin" = "false" -a "$darwin" = "false" -a "$nonstop" = "false" ] ; then
    MAX_FD_LIMIT=$(ulimit -H -n)
    if [ $? -eq 0 ] ; then
        if [ "$MAX_FD" = "maximum" -o "$MAX_FD" = "max" ] ; then
            MAX_FD="$MAX_FD_LIMIT"
        fi
        ulimit -n $MAX_FD
        if [ $? -ne 0 ] ; then
            warn "Could not set maximum file descriptor limit: $MAX_FD"
        fi
    else
        warn "Could not query maximum file descriptor limit: $MAX_FD_LIMIT"
    fi
fi

# Collect all arguments for the java command.
flags() {
    eval set -- "$DEFAULT_JVM_OPTS" "$JAVA_OPTS" "$GRADLE_OPTS" "\"-Dorg.gradle.appname=$APP_BASE_NAME\"" -classpath "\"$CLASSPATH\"" org.gradle.wrapper.GradleWrapperMain "$@"
}

# If wrapper jar doesn't exist, try to download or fallback to gradle
if [ ! -f "$CLASSPATH" ]; then
    WRAPPER_PROPERTIES="$APP_HOME/gradle/wrapper/gradle-wrapper.properties"
    if [ -f "$WRAPPER_PROPERTIES" ]; then
        DIST_URL=$(grep "distributionUrl" "$WRAPPER_PROPERTIES" | cut -d'=' -f2 | tr -d '\\' | tr -d '\r')
        DIST_ZIP_NAME=$(basename "$DIST_URL")
        DIST_NAME="${DIST_ZIP_NAME%.zip}"
        GRADLE_USER_HOME_DIR="${GRADLE_USER_HOME:-$HOME/.gradle}"
        GRADLE_ZIP_DEST="$GRADLE_USER_HOME_DIR/wrapper/dists/$DIST_NAME"

        # Check if already installed
        GRADLE_BIN=$(find "$GRADLE_ZIP_DEST" -name "gradle" -type f 2>/dev/null | head -n 1)
        if [ -n "$GRADLE_BIN" ] && [ -x "$GRADLE_BIN" ]; then
            exec "$GRADLE_BIN" "$@"
        fi

        # Download gradle wrapper jar directly
        mkdir -p "$APP_HOME/gradle/wrapper"
        echo "Downloading gradle-wrapper.jar..."
        curl -sLo "$CLASSPATH" "https://raw.githubusercontent.com/gradle/gradle/v8.7.0/gradle/wrapper/gradle-wrapper.jar" 2>/dev/null
    fi
fi

# Run Gradle Wrapper Main
eval set -- "$DEFAULT_JVM_OPTS" "$JAVA_OPTS" "$GRADLE_OPTS" "\"-Dorg.gradle.appname=$APP_BASE_NAME\"" -classpath "\"$CLASSPATH\"" org.gradle.wrapper.GradleWrapperMain "$@"
exec "$JAVACMD" "$@"
